namespace Spectre.Console.Cli.SourceGenerator.Emitters;

/// <summary>
/// Emits the SpectreMetadata marker attribute.
/// </summary>
internal static class AttributeEmitter
{
    /// <summary>
    /// The simple name of the marker attribute.
    /// </summary>
    public const string AttributeName = "SpectreMetadataAttribute";

    /// <summary>
    /// The fully qualified metadata name of the marker attribute.
    /// </summary>
    public const string AttributeFullName = "Spectre.Console.Cli.SpectreMetadataAttribute";

    /// <summary>
    /// Emits the marker attribute source code.
    /// </summary>
    public static string Emit()
    {
        return """
            // <auto-generated />
            #nullable enable

            namespace Spectre.Console.Cli
            {
                /// <summary>
                /// Marks a partial class for source generation of AOT-safe metadata.
                /// The marked class will be augmented to implement <see cref="Metadata.ICommandMetadataContext"/>.
                /// </summary>
                /// <example>
                /// <code>
                /// [SpectreMetadata]
                /// internal partial class MyAppMetadata { }
                ///
                /// var app = new CommandApp(null, new MyAppMetadata());
                /// </code>
                /// </example>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                [global::System.CodeDom.Compiler.GeneratedCode("Spectre.Console.Cli.SourceGenerator", "1.0.0")]
                internal sealed class SpectreMetadataAttribute : global::System.Attribute
                {
                }
            }
            """;
    }
}
